Repository Icinga/ipl-sql, pull requests merged in 2022-04, with the labels that each got.

#49 Query builder events
  src/Adapter/BaseAdapter.php
  src/Adapter/Mssql.php
  src/Adapter/Pgsql.php
  src/Contract/Adapter.php
  src/QueryBuilder.php
  tests/Pgsql/SelectTest.php
Labels: enhancement, cla/signed

#51 Remove transformation automatisms for PostgreSQL
  src/Adapter/Pgsql.php
  tests/Pgsql/SelectTest.php
Labels: cla/signed

#53 Connection: Cleanup results in `ping()`
  src/Connection.php
Labels: bug, cla/signed
